[build]
command = "npm run build && npm run export"
publish = "out"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200 

[[headers]]
    for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"